version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/LOGIN-WITH-GITHUB
    ports:
      - 3000:3000
      - 5000:5000
    image: app:react
    container_name: react_container
    command: yarn start

